### PR TITLE
feat(CSV): add feature export result table into simple CSV, separated by comma

### PR DESCRIPTION
**Pull request by clariokids**
still simple csv, download button in page "crawlPageResultsOnecrawlsimple"
as the meteor not update, there is some issues with my crawl
but for download i already test with error result, 
supposedly no problem with success one
will test again after resolve my meteor update

### CODE REVIEW

**Comment by guillim** [comment]
I am experiencing some issues while building it. I will let you know when i can test your PR

**Comment by clariokids** [comment]
yeah, i try like several time meteor reset 
don't update it
reinstall everything.
once runs, then it's ok
but sadly, because cannot update meteor, the jquery still deprecated

**Comment by clariokids** [comment]
anyway, the simple way of it

>     const hiddenElement = document.createElement('a');
>     hiddenElement.href = 'data:text/csv;charset=utf-8,' + encodeURI(csvData);
>     hiddenElement.target = '_blank';
>     hiddenElement.download = `${this.title}.csv`;
>     hiddenElement.click();

as csvData is string with , (comma) as cell separator, and break (\n) as next row
i'm not really good develop using meteor, so you can still build it as your data needed
you can try on your stable running web

**Comment by guillim** [comment]
tks @clariokids sorry for the delay, I was busy on other projects

**Comment by clariokids** [comment]
No worries

**Pull request merged**
